spring:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    url: jdbc:h2:file:./data
    driver-class-name: org.h2.Driver
    username: sa
    password:
    initialization-mode: always
  h2:
    console:
      enabled: true

logging:
  level:
    root: ERROR
    ru:
      skb:
        tech:
          test:
            springhibernatesecurity: DEBUG
